# -*- coding: utf-8 -*-
"""Bedürfniskatalog Schweiz. Jede Zeile: Segment, Bedürfnis, Produktidee und sieben Werte 1–5.

M Marktgrösse CH (1: <0,5 Mio. Umsatzpotenzial ... 5: >15 Mio.)
Z Zahlungsbereitschaft / Schmerz
S Selbstbedienung, abends machbar (5 = kein Verkaufsgespräch nötig)
W Wettbewerb (5 = kaum Anbieter, 1 = stark besetzt)  – Einschätzung, bei Finalisten geprüft
V Vorsprung (Schweizer Eigenheit, Fachwissen der Gründerperson)
K Kapital und Regulierung (5 = keine Bewilligung, kein Kapital)
D Eingebauter Vertrieb (Suchvolumen, Weiterempfehlung, Partner)
"""
K_ = [
# ---------------- Wohnen: Mieter
("Mieter", "Bewerbung gegen 50 Mitbewerber gewinnen", "Mietdossier mit Coach", 3,3,5,1,4,5,4),
("Mieter", "früher aus dem Mietvertrag ohne doppelte Miete", "Nachmieter-Lotse OR 264", 3,4,5,3,5,5,4),
("Mieter", "Kaution nach Auszug schnell zurück", "Kautions-Freigabe-Assistent", 1,3,5,3,4,5,2),
("Mieter", "Nebenkostenabrechnung verstehen", "NK-Erklärer", 2,2,5,3,4,5,3),
("Mieter", "Endreinigung mit Abnahmegarantie finden", "Reinigungs-Vermittlung", 3,3,4,1,3,4,3),
("Mieter", "Umzug organisieren", "Umzugs-Checkliste mit Partnern", 3,2,5,1,2,5,4),
("Mieter", "Mängel melden und Fristen kennen", "Mängel-Assistent", 2,3,5,3,4,5,3),
("Mieter", "Untermiete legal regeln", "Untermiet-Assistent OR 262", 1,2,5,4,4,5,2),
# ---------------- Wohnen: Eigentum
("Eigenheim", "Unterhalt bis Ende 2028 steuerlich nutzen", "Eigenmietwert-Planer", 3,4,5,2,3,5,4),
("Eigenheim", "Belege für Grundstückgewinnsteuer aufbewahren", "Digitale Hausakte", 3,3,5,1,3,5,3),
("Eigenheim", "Heizungsersatz planen und Förderung finden", "Heizungs-Navigator", 3,3,5,2,2,5,4),
("Eigenheim", "Handwerker vertrauenswürdig finden", "Handwerker-Bewertungen", 4,3,5,1,2,5,3),
("Eigenheim", "Solarstrom optimal nutzen und abrechnen", "PV-Eigenverbrauch-Coach", 3,3,5,2,2,5,3),
("Eigenheim", "Hypothek verlängern ohne Bankgespräch", "Hypotheken-Vergleich", 5,4,4,1,1,3,4),
("Eigenheim", "Liegenschaft verkaufen ohne Makler", "Privatverkauf-Assistent", 4,4,4,2,3,5,3),
("Eigenheim", "Gebäudeversicherung und Schäden melden", "Schadenmelde-Assistent", 2,2,5,3,2,5,2),
# ---------------- Stockwerkeigentum / Vermieter
("STWE", "Gemeinschaft ohne Verwalter führen", "Selbstverwaltungs-Software", 3,3,5,2,4,5,3),
("STWE", "Erneuerungsfonds richtig bemessen", "Fonds-Planer", 2,3,5,3,4,5,3),
("STWE", "Versammlung digital abhalten", "Versammlungs-App", 2,2,5,3,3,5,3),
("Privatvermieter", "Mieter sicher auswählen", "Bewerber-Prüfung", 3,3,5,2,4,4,3),
("Privatvermieter", "Mietzins korrekt anpassen (Referenzzins)", "Mietzins-Assistent", 2,3,5,1,4,5,3),
("Privatvermieter", "Mietvertrag nach Kanton korrekt", "Vertragsgenerator", 2,3,5,2,4,5,3),
("Privatvermieter", "Buchhaltung und Nebenkosten", "Vermietersoftware", 3,3,5,1,4,5,3),
("Privatvermieter", "Ferienwohnung legal vermieten (Gemeinderegeln)", "Kurzzeit-Regel-Check", 1,2,5,4,3,5,2),
# ---------------- Familie
("Familie", "Kita-Platz und Subventionen finden", "Kita-Finder mit Subventionsrechner", 2,3,5,3,3,5,4),
("Familie", "Ferienbetreuung organisieren", "Ferienangebots-Plattform", 2,2,5,3,2,5,3),
("Familie", "Familienkalender und Aufgaben teilen", "Familien-App", 3,2,5,1,1,5,3),
("Familie", "Kinderzulagen und Formulare", "Familien-Formularhelfer", 1,2,5,3,3,5,2),
("Familie", "Nachhilfe finden", "Nachhilfe-Marktplatz", 3,3,4,1,2,5,3),
("Familie", "Übertritt Sek/Gymi vorbereiten", "Gymi-Prüfungstrainer", 3,4,5,2,4,5,4),
("Familie", "Hausaufgaben begleiten nach Lehrplan 21", "KI-Lernbegleiter LP21", 4,3,5,2,3,5,3),
("Familie", "Babysitter vertrauenswürdig finden", "Babysitter-Plattform", 2,3,4,1,1,4,3),
# ---------------- Jugendliche / Berufsbildung
("Berufswahl", "Lehrstelle finden", "Lehrstellen-Coach", 3,3,5,1,3,5,4),
("Berufswahl", "Eignungstest bestehen (Multicheck, Basic-Check)", "Eignungstest-Trainer", 3,4,5,1,4,5,4),
("Berufswahl", "Bewerbungsdossier für Lehrstelle", "Lehrstellen-Bewerbungs-KI", 2,3,5,2,3,5,4),
("Berufswahl", "Schnupperlehren organisieren", "Schnupper-Planer", 1,2,5,3,3,5,3),
("Lernende", "Lehrabschlussprüfung bestehen", "QV-Prüfungstrainer je Beruf", 4,4,5,3,4,5,4),
("Lernende", "Berufsschulstoff verstehen", "KI-Tutor Berufsschule (ABU)", 4,3,5,2,4,5,3),
("Lehrbetriebe", "Lernende betreuen und dokumentieren", "Lernenden-Management", 3,3,3,2,3,5,2),
("Weiterbildung", "eidg. Fachausweis/Diplom bestehen", "Prüfungstrainer Höhere Berufsbildung", 3,5,5,2,4,5,4),
# ---------------- Arbeit
("Stellensuchende", "Bewerbung auf Schweizer Standard", "Bewerbungs-KI CH", 3,3,5,1,2,5,4),
("Stellensuchende", "RAV-Pflichten erfüllen", "RAV-Assistent", 2,2,5,3,3,5,3),
("Angestellte", "Lohn vergleichen und verhandeln", "Lohnrechner/Verhandlungscoach", 3,2,5,2,2,5,4),
("Angestellte", "Arbeitszeugnis entschlüsseln", "Zeugnis-Analyse", 2,3,5,2,4,5,4),
("Angestellte", "Kündigung und Rechte verstehen", "Arbeitsrechts-Assistent", 2,3,5,2,3,5,3),
("Temporär", "Einsätze und Stunden erfassen", "Stundenrapport-App", 2,2,4,2,2,5,2),
("Grenzgänger", "Steuern und Sozialversicherung korrekt", "Grenzgänger-Assistent", 2,3,5,3,4,5,3),
("Expats", "Ankommen: Anmeldung, Krankenkasse, Bank", "Expat-Onboarding", 3,3,5,2,3,4,4),
# ---------------- Geld / Steuern / Vorsorge
("Steuern", "Steuererklärung schnell ausfüllen", "KI-Steuerhelfer", 5,3,5,1,3,5,4),
("Steuern", "Quellensteuer zurückholen (NOV)", "Quellensteuer-Lotse", 3,4,5,2,4,5,4),
("Steuern", "Steuern optimieren (3a, Einkauf PK)", "Steuer-Optimierer", 4,4,5,2,3,5,4),
("Vorsorge", "Kapital oder Rente bei Pensionierung", "Pensionierungsplaner", 4,4,4,2,3,5,3),
("Vorsorge", "AHV-Lücken erkennen", "AHV-Lücken-Check", 2,3,5,3,4,5,3),
("Vorsorge", "Freizügigkeitsgelder finden", "Guthaben-Suche", 2,3,5,3,4,5,3),
("Budget", "Fixkosten senken (Abos, Versicherungen)", "Fixkosten-Coach", 4,3,5,2,2,4,4),
("Schulden", "Betreibung vermeiden und Schulden ordnen", "Schulden-Lotse", 2,3,5,3,3,4,3),
# ---------------- Gesundheit
("Gesundheit", "Richtige Franchise und Modell wählen", "Krankenkassen-Optimierer", 5,3,5,1,2,3,5),
("Gesundheit", "Arztrechnung nach neuem Tarif TARDOC prüfen", "Rechnungs-Check TARDOC", 3,3,5,4,4,4,3),
("Gesundheit", "Belege bei Zusatzversicherung einreichen", "Rückforderungs-Assistent", 3,2,5,2,2,4,2),
("Gesundheit", "Therapeut:in (Psychotherapie) mit Platz finden", "Therapieplatz-Finder", 3,4,4,3,2,5,4),
("Gesundheit", "Zahnarztkosten vergleichen", "Zahnkosten-Vergleich", 3,3,5,3,2,5,4),
("Gesundheit", "Chronische Krankheit managen", "Patienten-Tagebuch", 3,2,5,1,1,4,2),
("Pflege", "Pflegeheim finden und finanzieren", "Pflege-Finanzierungs-Lotse", 3,4,4,3,3,5,3),
("Pflege", "Ergänzungsleistungen beantragen", "EL-Antrags-Assistent", 2,4,4,3,3,5,3),
# ---------------- Lebensereignisse
("Todesfall", "Alles erledigen nach einem Todesfall", "Nachlass-Lotse", 3,4,5,3,4,5,4),
("Vorsorge-Dokumente", "Testament, Vorsorgeauftrag, Patientenverfügung", "Vorsorgedokumente digital", 3,3,5,2,3,5,4),
("Heirat", "Hochzeit planen", "Hochzeitsplaner CH", 3,3,5,1,1,5,4),
("Trennung", "Unterhalt und Scheidung berechnen", "Unterhaltsrechner", 2,4,5,3,3,5,4),
("Geburt", "Mutterschaft und Formalitäten", "Baby-Formular-Lotse", 2,2,5,3,3,5,3),
("Einbürgerung", "Einbürgerungstest bestehen", "Einbürgerungs-Trainer je Gemeinde", 3,4,5,1,4,5,4),
("Führerausweis", "Theorieprüfung bestehen", "Theorie-Trainer", 3,3,5,1,2,5,4),
("Militär", "Dienstverschiebung und EO", "Dienst-Assistent", 1,2,5,4,3,5,2),
# ---------------- Mobilität / Freizeit
("Auto", "MFK-Prüfung vorbereiten", "MFK-Checker", 2,3,5,3,3,5,3),
("Auto", "Occasion kaufen ohne Reinfall", "Occasions-Check", 3,3,5,2,2,5,4),
("Velo", "E-Bike Service und Diebstahl", "Velo-Pass", 2,2,5,3,2,5,3),
("Hund", "Hundegesetze je Kanton und Kurse", "Hunde-App CH", 2,2,5,3,3,5,3),
("Sport", "Verein führen (Mitglieder, Beiträge)", "Vereinssoftware", 3,3,5,1,2,5,3),
("Reisen", "Flugverspätung entschädigt erhalten", "Fluggastrechte-Claim", 3,3,5,1,2,5,4),
("Freizeit", "Ausflüge mit Kindern", "Ausflugs-Plattform", 2,1,5,1,1,5,4),
("Garten", "Schrebergarten/Pflanzenpflege", "Garten-App", 1,1,5,2,1,5,2),
# ---------------- Selbständige / Gründer
("Selbständige", "AHV-Anerkennung als Selbständiger", "Selbständigkeits-Lotse", 2,3,5,3,4,5,3),
("Selbständige", "Buchhaltung und MWST ohne Treuhänder", "KI-Buchhaltung Einzelfirma", 4,3,5,1,2,5,3),
("Selbständige", "Offerten und Rechnungen", "Rechnungs-App", 4,3,5,1,1,5,3),
("Gründer", "Firma gründen", "Gründungsplattform", 3,3,5,1,2,5,4),
("Freelancer", "Aufträge finden", "Freelancer-Marktplatz CH", 3,3,4,1,1,5,3),
("Selbständige", "Sozialversicherungen und Vorsorge als Selbständiger", "Selbständigen-Vorsorge-Check", 2,3,5,3,3,5,3),
("Selbständige", "Scheinselbständigkeit vermeiden", "Status-Check", 1,3,5,4,3,5,2),
("Nebenerwerb", "Nebenerwerb korrekt anmelden", "Nebenerwerb-Lotse", 2,2,5,3,3,5,3),
# ---------------- KMU allgemein
("KMU", "Anrufe nicht verpassen", "KI-Telefonassistent Mundart", 5,4,3,1,4,4,3),
("KMU", "Sitzungen protokollieren (Mundart)", "Mundart-Protokoll", 4,3,5,1,4,5,3),
("KMU", "Datenschutz revDSG erfüllen", "revDSG-Generator", 3,3,5,2,3,5,3),
("KMU", "Lohnbuchhaltung inkl. Quellensteuer", "Lohn-Software Kleinstbetriebe", 4,3,4,1,3,4,2),
("KMU", "Personal finden", "Stellen-Plattform", 4,3,4,1,1,5,3),
("KMU", "Google-Bewertungen verbessern", "Bewertungs-Tool", 3,3,5,1,1,5,3),
("KMU", "Nachfolge regeln", "Nachfolge-Marktplatz", 4,4,3,2,2,5,3),
("KMU", "Arbeitssicherheit EKAS/SUVA dokumentieren", "Sicherheits-Doku-App", 3,3,4,3,3,5,2),
# ---------------- Gastro / Detailhandel
("Gastro", "Hygiene-Selbstkontrolle dokumentieren", "Digitale Hygiene-Kontrolle", 3,3,4,3,3,5,3),
("Gastro", "Allergene deklarieren", "Allergen-Karte", 2,3,5,3,3,5,3),
("Gastro", "Schichtplanung", "Dienstplan-App", 3,3,4,1,2,5,3),
("Gastro", "Reservationen", "Reservationssystem", 3,3,4,1,1,5,3),
("Detailhandel", "Online verkaufen in der Schweiz", "Shop-Baukasten CH", 3,3,5,1,1,5,3),
("Detailhandel", "Export in die EU (MWST, Zoll)", "Export-Assistent", 2,4,5,3,3,5,2),
("Gastro", "Food Waste reduzieren", "Restposten-App", 2,2,4,1,1,5,4),
("Detailhandel", "Inventar und Nachbestellung", "Lager-App", 3,3,4,1,1,5,2),
# ---------------- Handwerk / Bau
("Handwerk", "Offerten schnell schreiben", "KI-Offerte per Sprache", 3,4,4,2,3,5,3),
("Handwerk", "Rapporte und Fotos", "Rapport-App", 3,3,4,2,3,5,2),
("Handwerk", "Mietertermine koordinieren", "Mietertermin-Link", 2,3,4,3,5,5,3),
("Bau", "Baubewilligung verstehen", "Baugesuch-Assistent", 3,4,4,3,3,5,3),
("Bau", "Baukosten schätzen", "Baukosten-Rechner", 3,3,5,2,3,5,4),
("Handwerk", "Lernende rekrutieren", "Lehrbetrieb-Recruiting", 2,3,3,2,2,5,2),
("Bau", "Mängel bei Neubau dokumentieren (Garantie)", "Neubau-Mängel-App", 2,3,5,3,4,5,3),
("Handwerk", "Material bestellen", "Einkaufs-Plattform", 3,2,3,1,1,3,2),
# ---------------- Gesundheitsberufe
("Therapeuten", "Abrechnung EMR/ASCA", "Praxis-Software Komplementär", 3,3,4,1,2,5,2),
("Psychotherapie", "Anordnungsmodell-Administration", "Psycho-Praxis-Software", 3,3,4,2,2,5,2),
("Spitex privat", "Einsätze und Rapporte", "Spitex-App", 3,3,3,1,2,4,2),
("Ärzte", "Dokumentation per Sprache (Mundart)", "Mundart-Arztbericht", 4,4,3,2,4,4,3),
("Pflegende Angehörige", "Anstellung bei Spitex/Entlastung", "Angehörigen-Lotse", 2,3,4,3,3,4,3),
("Apotheken", "Impf- und Beratungstermine", "Termin-Tool", 2,2,4,1,1,5,2),
("Physio", "Übungen für Patienten", "Übungs-App", 2,2,4,1,1,5,2),
("Tierärzte", "Termine und Erinnerungen", "Tierarzt-App", 2,2,4,2,1,5,2),
# ---------------- Landwirtschaft / Energie
("Landwirtschaft", "Direktzahlungen und Agate-Formulare", "Agrar-Admin-Assistent", 3,3,4,3,4,5,2),
("Landwirtschaft", "Direktvermarktung Hofladen", "Hofladen-Shop", 2,2,5,2,2,5,3),
("Energie", "Stromgemeinschaft LEG abrechnen", "LEG-Software", 3,3,4,1,3,4,3),
("Energie", "Energieausweis GEAK vorbereiten", "GEAK-Vorbereitung", 2,3,4,3,3,5,2),
("Energie", "Strompreis und Tarife verstehen", "Stromtarif-Vergleich", 3,2,5,3,2,5,4),
("Landwirtschaft", "Hofnachfolge", "Hofnachfolge-Plattform", 1,3,4,4,2,5,2),
("Energie", "E-Auto zuhause laden abrechnen (Mieter)", "Lade-Abrechnung", 2,3,4,2,3,4,2),
("Landwirtschaft", "Aushilfen finden (Ernte)", "Erntehelfer-Plattform", 1,3,4,3,2,4,2),
# ---------------- Gemeinden / Vereine / Bildung
("Gemeinden", "Gemeindeversammlung protokollieren", "Protokoll-Tool Gemeinden", 2,3,3,3,4,5,2),
("Vereine", "GV organisieren und Beiträge einziehen", "Vereins-GV-Tool", 2,2,5,1,2,5,3),
("Lehrpersonen", "Unterricht nach LP21 vorbereiten", "KI-Unterrichtsplaner LP21", 3,3,5,2,3,5,4),
("Lehrpersonen", "Beurteilung und Zeugnisse", "Beurteilungs-Tool", 2,2,4,2,3,5,2),
("Schulen", "Elternkommunikation", "Schul-App", 3,2,3,1,1,5,2),
("Musikschulen", "Stundenplan und Abrechnung", "Musikschul-Software", 2,3,4,2,2,5,2),
("Kitas", "Betreuungsverträge und Abrechnung", "Kita-Software", 3,3,4,2,2,5,2),
("Sportvereine", "J+S-Kurse administrieren", "J+S-Assistent", 2,2,4,4,4,5,2),
# ---------------- Senioren
("Senioren", "Digitale Hilfe am Handy", "Senioren-Handyhilfe", 2,2,4,3,2,5,3),
("Senioren", "Wohnen im Alter planen", "Alterswohn-Lotse", 2,3,4,3,3,5,3),
("Senioren", "Nachlass zu Lebzeiten ordnen", "Lebensordner digital", 3,3,5,2,3,5,3),
("Senioren", "Betrugsmaschen erkennen", "Betrugs-Check", 2,2,5,3,2,5,3),
("Senioren", "Mobilität ohne Auto", "Fahrdienst-Vermittlung", 2,3,3,2,2,4,2),
# ---------------- Studierende / Junge
("Studierende", "WG-Zimmer finden", "WG-Plattform", 2,2,5,1,1,5,4),
("Studierende", "Stipendien finden", "Stipendien-Finder", 1,3,5,3,3,5,3),
("Studierende", "Prüfungen lernen", "KI-Lernkarten", 3,3,5,1,1,5,4),
("Junge", "Erste Steuererklärung/Budget", "Erwachsenwerden-Lotse", 2,2,5,3,2,5,4),
("Junge", "Erster Mietvertrag, Versicherungen", "Start-ins-Leben-Paket", 2,2,5,3,3,4,3),
# ---------------- Recht / Konsum
("Konsum", "Abo kündigen", "Kündigungsdienst", 3,2,5,2,2,5,4),
("Konsum", "Garantie und Gewährleistung durchsetzen", "Garantie-Assistent", 2,3,5,3,3,5,3),
("Recht", "Rechtsfrage schnell klären", "KI-Rechtsauskunft CH", 4,3,5,2,3,4,4),
("Recht", "Betreibung einleiten gegen Schuldner", "Inkasso-Assistent", 3,4,5,2,3,4,3),
("Recht", "Schlichtungsverfahren vorbereiten", "Schlichtungs-Lotse", 2,3,5,3,3,5,3),
("Verkehr", "Busse anfechten", "Bussen-Check", 1,3,5,3,3,5,3),
# ---------------- Versicherung / Finanzen
("Versicherung", "Deckungslücken erkennen", "Versicherungs-Check", 4,3,5,1,2,2,4),
("Versicherung", "Schaden schnell melden und durchsetzen", "Schadenfall-Assistent", 2,3,5,3,2,5,2),
("Finanzen", "Vermögen und Konten im Überblick", "Finanz-Übersicht CH", 3,2,5,2,2,3,3),
("Finanzen", "ETF/3a verstehen", "Finanzbildung", 3,2,5,1,1,5,4),
("Finanzen", "Erbe erhalten: was tun?", "Erbschafts-Lotse", 3,4,5,3,3,5,4),
# ---------------- Tourismus / Gastgeber
("Tourismus", "Ferienwohnung vermieten (Kurtaxe, Regeln)", "Gastgeber-Assistent CH", 2,3,5,2,3,5,3),
("Tourismus", "Gästekommunikation mehrsprachig", "Gäste-KI", 2,3,5,1,1,5,3),
("Tourismus", "Bergbahn/Region: Gästedaten nutzen", "Destinations-Analytics", 2,3,2,3,2,5,1),
# ---------------- Online-Händler / Kreative
("Online-Händler", "Produkttexte und Übersetzungen DE/FR/IT", "Mehrsprachige Shop-Texte", 3,3,5,1,2,5,3),
("Online-Händler", "Retouren und Versand CH", "Versand-Tool", 3,3,4,1,1,5,2),
("Kreative", "Rechte an Bildern/Musik klären", "Rechte-Check", 1,2,5,3,2,5,2),
("Kreative", "Aufträge und Honorare", "Honorarrechner", 2,2,5,3,2,5,3),
# ---------------- Immobilienprofis als Nutzer
("Bewirtschafter", "Prüfung eidg. Fachausweis Immobilienbewirtschaftung bestehen", "Prüfungstrainer Immobilien", 1,5,5,3,5,5,4),
("Bewirtschafter", "Mieterbriefe schnell und korrekt", "Vorlagen-KI Bewirtschaftung", 2,3,5,3,5,5,3),
("Hauswarte", "Rundgänge und Aufträge dokumentieren", "Hauswart-App", 2,3,4,2,4,5,2),
("Makler", "Inserate und Exposés", "Exposé-KI", 2,3,5,1,2,5,3),
# ---------------- Weiterbildung (breit)
("Weiterbildung", "Prüfung Technische Kaufleute bestehen", "Prüfungstrainer TK", 2,5,5,4,3,5,4),
("Weiterbildung", "Prüfung Sachbearbeitung/HR/Marketing (edupool, KV)", "Prüfungstrainer KV-Weiterbildung", 3,5,5,3,3,5,4),
("Weiterbildung", "Sprachzertifikat für Einbürgerung (fide)", "fide-Trainer", 2,4,5,3,4,5,4),
("Weiterbildung", "Treuhand-Fachausweis", "Prüfungstrainer Treuhand", 2,5,5,4,3,5,4),
# ---------------- Behörden / Staat
("Behörden", "Formulare ausfüllen (Gemeinde, Kanton)", "Formular-KI", 3,2,5,3,3,5,3),
("Behörden", "Umzug melden, Ausweise", "Behörden-Checkliste", 2,1,5,1,2,5,3),
("Behörden", "Bewilligungen für Anlässe", "Anlass-Bewilligungs-Lotse", 1,3,5,4,3,5,2),
# ---------------- Nachhaltigkeit / Kreislauf
("Nachhaltigkeit", "Möbel und Geräte reparieren lassen", "Reparatur-Plattform", 2,2,4,2,1,5,3),
("Nachhaltigkeit", "CO2-Bericht für KMU", "KMU-CO2-Bilanz", 3,3,4,2,2,5,2),
("Nachhaltigkeit", "Secondhand verkaufen", "Wiederverkaufs-Assistent", 3,2,5,1,1,5,3),
# ---------------- Haustiere
("Haustiere", "Tiersitter finden", "Tiersitter-Plattform", 2,3,4,1,1,5,3),
("Haustiere", "Tierarztkosten versichern", "Tierversicherungs-Vergleich", 2,3,5,2,1,3,3),
]
