# -*- coding: utf-8 -*-
"""Texte der drei Testseiten. Beispielzahlen sind nachgerechnet (siehe README)."""

IMPRESSUM_DE = ('Verantwortlich: [Vorname Name], [Strasse Nr.], [PLZ Ort], Schweiz · E-Mail: [adresse] · '
                'Datenschutz: Ihre Angaben dienen nur der Benachrichtigung zum Start und werden nicht weitergegeben. '
                'Löschung jederzeit per E-Mail.')

SEITEN = {
"weg": dict(
    lang="de", marke="Hausrunde", title="Hausrunde – WEG selbst verwalten",
    desc="Wirtschaftsplan, Hausgeld, Eigentümerversammlung und Beschluss-Sammlung für selbstverwaltete WEGs in einer App.",
    nav="Zur Warteliste", eyebrow="Für selbstverwaltete Wohnungseigentümergemeinschaften",
    h1="Ihre WEG selbst verwalten. Ohne Excel und Ordnerchaos.",
    lead="Keine Verwaltung gefunden oder zu teuer? Hausrunde führt Sie durch Wirtschaftsplan, Hausgeld, "
         "Jahresabrechnung und Eigentümerversammlung, mit allen Fristen nach dem WEG.",
    preis="1,50 € pro Einheit und Monat", preis_zusatz="mindestens 12 € · Einführungspreis für die ersten 12 Monate",
    form=dict(name="wl-weg", danke="danke.html", email="E-Mail", anzahl="Einheiten in Ihrer WEG",
              rolle="Sie sind", optionen=["Verwaltungsbeirat", "Eigentümer/in", "Hausverwalter/in", "Andere"],
              knopf="Auf die Warteliste", hinweis="Hausrunde ist in Entwicklung. Wir schreiben Ihnen einmal, wenn es losgeht."),
    tabelle=dict(titel="Hausgeld nach Miteigentumsanteilen", bsp="Beispiel",
                 k1="Einheit", k2="MEA", k3="pro Monat",
                 zeilen=[("Whg. 1", "180/1000", 82, "450 €"), ("Whg. 2", "140/1000", 64, "350 €"),
                         ("Whg. 3", "140/1000", 64, "350 €"), ("Whg. 4", "220/1000", 100, "550 €"),
                         ("Whg. 5", "160/1000", 73, "400 €"), ("Whg. 6", "160/1000", 73, "400 €")],
                 summe=("Total", "1000/1000", "2'500 €".replace("'", ".")),
                 fuss="Wirtschaftsplan 24.000 € plus Erhaltungsrücklage 6.000 € im Jahr, automatisch verteilt."),
    f_titel="Was Hausrunde für Ihre Gemeinschaft erledigt",
    funktionen=[
        ("Wirtschaftsplan und Hausgeld", "Kosten erfassen, nach Miteigentumsanteilen oder eigenem Schlüssel verteilen, Hausgeld-Übersicht für alle.", "§ 28 WEG"),
        ("Jahresabrechnung", "Belege hochladen, Abrechnung je Einheit, Nachzahlung oder Guthaben auf einen Blick.", "§ 28 Abs. 2 WEG"),
        ("Eigentümerversammlung", "Einladung mit Tagesordnung, Fristenwarnung, Vollmachten, Abstimmung, Protokollvorlage. Online-Teilnahme, wenn beschlossen.", "Einladungsfrist 3 Wochen, § 24 Abs. 4 WEG · § 23 Abs. 1a WEG"),
        ("Beschluss-Sammlung", "Jeder Beschluss wird automatisch mit Datum und Ergebnis erfasst und bleibt für alle einsehbar.", "§ 24 Abs. 7 WEG"),
        ("Erhaltungsrücklage", "Plan, welche Bauteile wann fällig werden, und wie viel jährlich zurückgelegt werden sollte.", "§ 19 Abs. 2 Nr. 4 WEG"),
        ("Belege und Dokumente", "Teilungserklärung, Verträge, Versicherungen, Rechnungen an einem Ort, für alle Eigentümer lesbar.", ""),
    ],
    faq_titel="Häufige Fragen",
    faq=[("Darf eine WEG ohne Verwalter auskommen?", "Ja. Ohne Verwalter vertreten alle Eigentümer die Gemeinschaft gemeinschaftlich (§ 9b WEG). Hausrunde hilft, diese Aufgaben geordnet zu erledigen."),
         ("Wo liegt das Geld der Gemeinschaft?", "Auf dem Konto Ihrer Gemeinschaft bei Ihrer Bank. Hausrunde verwaltet kein Geld."),
         ("Wer steht dahinter?", "Ein Immobilienbewirtschafter aus der Schweiz, der die Abläufe aus der täglichen Praxis kennt."),
         ("Was kostet es nach dem Einführungsjahr?", "Der reguläre Preis wird vor Ablauf mitgeteilt; Sie können jederzeit kündigen.")],
    footer=IMPRESSUM_DE,
    danke_h="Danke, Sie sind auf der Warteliste.",
    danke_t="Wir melden uns, sobald Hausrunde für Ihre Gemeinschaft bereit ist. Bis dahin erhalten Sie keine weiteren E-Mails."),

"stwe": dict(
    lang="de-CH", marke="Hausrunde", title="Hausrunde – Stockwerkeigentum selbst verwalten",
    desc="Budget, Abrechnung nach Wertquoten, Erneuerungsfonds und Versammlung für selbstverwaltete Stockwerkeigentümergemeinschaften.",
    nav="Zur Warteliste", eyebrow="Für Stockwerkeigentümergemeinschaften ohne Verwaltung",
    h1="Ihre Gemeinschaft, ordentlich verwaltet. Auch ohne Verwaltung.",
    lead="Die Verwaltung hat gekündigt oder ist zu teuer? Hausrunde führt Sie durch Budget, Abrechnung nach "
         "Wertquoten, Erneuerungsfonds und die Versammlung nach ZGB.",
    preis="CHF 2 pro Einheit und Monat", preis_zusatz="mindestens CHF 15 · Einführungspreis für die ersten 12 Monate",
    form=dict(name="wl-stwe", danke="danke.html", email="E-Mail", anzahl="Einheiten in Ihrer Gemeinschaft",
              rolle="Sie sind", optionen=["Verwaltungsausschuss", "Stockwerkeigentümer/in", "Verwaltung", "Andere"],
              knopf="Auf die Warteliste", hinweis="Hausrunde ist in Entwicklung. Wir schreiben Ihnen einmal, wenn es losgeht."),
    tabelle=dict(titel="Akonto nach Wertquoten", bsp="Beispiel",
                 k1="Einheit", k2="Wertquote", k3="pro Quartal",
                 zeilen=[("Whg. 1", "250 ‰", 100, "CHF 2'250"), ("Whg. 2", "200 ‰", 80, "CHF 1'800"),
                         ("Whg. 3", "200 ‰", 80, "CHF 1'800"), ("Whg. 4", "180 ‰", 72, "CHF 1'620"),
                         ("Whg. 5", "170 ‰", 68, "CHF 1'530")],
                 summe=("Total", "1000 ‰", "CHF 9'000"),
                 fuss="Budget CHF 27'000 plus Einlage Erneuerungsfonds CHF 9'000 im Jahr, automatisch verteilt."),
    f_titel="Was Hausrunde für Ihre Gemeinschaft erledigt",
    funktionen=[
        ("Budget und Akonto", "Kosten erfassen, nach Wertquoten oder Sonderschlüssel verteilen, Akontorechnungen für alle.", "ZGB Art. 712h"),
        ("Jahresrechnung", "Belege hochladen, Abrechnung je Einheit, Nachzahlung oder Guthaben auf einen Blick.", "ZGB Art. 712m"),
        ("Versammlung", "Einladung mit Traktanden, Vollmachten, Abstimmung nach Köpfen und Wertquoten, Protokoll und Beschlussbuch.", "Protokollpflicht ZGB Art. 712n"),
        ("Erneuerungsfonds", "Plan, welche Bauteile wann fällig werden, und wie viel die Gemeinschaft jährlich einlegen sollte.", "ZGB Art. 712m Abs. 1 Ziff. 5"),
        ("Gebäude automatisch erfasst", "Adresse eingeben: Baujahr, Heizungsart und Wohnungen kommen aus dem eidgenössischen Gebäude- und Wohnungsregister. Belege und Reglement an einem Ort.", "Daten aus dem GWR"),
        ("Vergleich mit ähnlichen Häusern", "Was zahlen vergleichbare Gemeinschaften für Heizung, Hauswartung, Versicherung oder ein neues Dach? Anonym, erst ab 10 vergleichbaren Gebäuden.", "Nur mit Ihrer Zustimmung, nie Personendaten"),
    ],
    faq_titel="Häufige Fragen",
    faq=[("Braucht eine Stockwerkeigentümergemeinschaft einen Verwalter?", "Nein, das Gesetz verlangt keinen. Wird keiner bestellt, kann jeder Stockwerkeigentümer die Ernennung durch das Gericht verlangen (ZGB Art. 712q); viele kleine Gemeinschaften verwalten sich selbst."),
         ("Wo liegt das Geld der Gemeinschaft?", "Auf dem Konto Ihrer Gemeinschaft bei Ihrer Bank. Hausrunde verwaltet kein Geld."),
         ("Sind virtuelle Versammlungen erlaubt?", "Nach heutiger Lehre ja, wenn Ihr Reglement es vorsieht. Hausrunde unterstützt beides."),
         ("Wo sind die Daten?", "Auf Servern in der Schweiz oder der EU, nach Datenschutzgesetz.")],
    footer=IMPRESSUM_DE,
    danke_h="Danke, Sie sind auf der Warteliste.",
    danke_t="Wir melden uns, sobald Hausrunde für Ihre Gemeinschaft bereit ist. Bis dahin erhalten Sie keine weiteren E-Mails."),

"uk": dict(
    lang="en-GB", marke="Walkround", title="Walkround – AI tenancy inventory for £15",
    desc="Walk the property with your phone. Walkround writes a timestamped, deposit-scheme-ready inventory and compares it at check-out.",
    nav="Join the waitlist", eyebrow="For self-managing landlords in England and Wales",
    h1="Your tenancy inventory in 15 minutes, for £15.",
    lead="Walk each room with your phone. Walkround logs every item and its condition, keeps the original timestamped "
         "photos, and compares everything at check-out. Inventory clerks typically charge from £95.",
    preis="£15 per report", preis_zusatz="check-in or check-out · launch price",
    form=dict(name="wl-uk", danke="danke.html", email="Email", anzahl="Properties you let",
              rolle="You are", optionen=["Landlord", "Letting agent", "Tenant", "Other"],
              knopf="Join the waitlist", hinweis="Walkround is in development. We will email you once when it launches."),
    tabelle=dict(titel="Check-out comparison", bsp="Example",
                 k1="Room", k2="Items", k3="Changes",
                 zeilen=[("Kitchen", "34", 100, "1"), ("Living room", "21", 62, "0"),
                         ("Bedroom", "18", 53, "2"), ("Bathroom", "16", 47, "1")],
                 summe=("Total", "89", "4"),
                 fuss="Each change is shown as a before-and-after pair with the original photos and timestamps."),
    f_titel="What Walkround does",
    funktionen=[
        ("Guided walk-through", "Room by room prompts so nothing is missed: walls, floors, fixtures, appliances, meters, keys.", ""),
        ("AI-written inventory", "Items and condition are described for you. You review and adjust before signing.", ""),
        ("Original evidence only", "Photos are never edited or generated. Each one keeps its timestamp.", ""),
        ("Check-out comparison", "Retake the same angles at the end of the tenancy and see every change side by side.", ""),
        ("Signatures", "Tenant and landlord sign on screen; both receive the PDF.", ""),
        ("Deposit dispute pack", "Before-and-after pairs and notes, ready to upload to your deposit scheme.", "TDS · DPS · mydeposits"),
    ],
    faq_titel="Questions",
    faq=[("Will deposit schemes accept it?", "Adjudicators look for dated photos from check-in and check-out and clear condition notes. Walkround produces exactly that; the decision always rests with the scheme."),
         ("Who is behind Walkround?", "A property manager from Switzerland who carries out move-in and move-out inspections as part of the job."),
         ("Do I need an app?", "No. It runs in your phone's browser.")],
    footer='Walkround is a project in preparation by [Name], [Address], Switzerland · Contact: [email] · Your email is only used to notify you about the launch and is never shared.',
    danke_h="Thanks, you're on the waitlist.",
    danke_t="We'll email you once when Walkround is ready. Nothing else until then."),
}
